# Generated by Django 3.0.8 on 2020-09-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VideoLib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('token', models.CharField(max_length=32)),
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('mobile_no', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255)),
                ('sex', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'video_lib_user',
            },
        ),
    ]
